version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    #network_mode: host
    networks:
      - click_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    #network_mode: host
    networks:
      - click_network

  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile-clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    #network_mode: host
    networks:
      - click_network
    command: /bin/bash -c "/entrypoint.sh"

  python:
    image: python:3.10.10
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    #network_mode: host
    networks:
      - click_network
    command: /bin/bash -c "chmod 777 /app && tail -f /dev/null"  # Добавляем команду chmod
    #command: tail -f /dev/null # Keep the container running

  airflow:
    image: apache/airflow:2.3.0
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow

      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0

      - AIRFLOW__CORE__FERNET_KEY=b0a_36xVARWfsP1QRhS2GM3MwrDzsO0KGM4PPpwE0Uc=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=2
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_data:/opt/airflow
      - /mnt/share/python_scripts/DWH/dags:/opt/airflow/dags/linked_ETL_dags

      
      
    #network_mode: host
    networks:
      - click_network
    depends_on:
      - postgres
      - redis
    restart: always
    command: webserver

  scheduler:
    image: apache/airflow:2.3.0
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow


      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=b0a_36xVARWfsP1QRhS2GM3MwrDzsO0KGM4PPpwE0Uc=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=2
    volumes:
      - ./airflow_data:/opt/airflow
    #network_mode: host
    networks:
      - click_network
    depends_on:
      - airflow
    restart: always
    command: scheduler

  worker:
    image: apache/airflow:2.3.0
    container_name: airflow_worker
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow


      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0

      - AIRFLOW__CORE__FERNET_KEY=b0a_36xVARWfsP1QRhS2GM3MwrDzsO0KGM4PPpwE0Uc=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=2
    volumes:
      - ./airflow_data:/opt/airflow
    #network_mode: host
    networks:
      - click_network
    depends_on:
      - airflow
    command: celery worker

  triggerer:
    image: apache/airflow:2.3.0
    container_name: airflow_triggerer
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow

      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0

      - AIRFLOW__CORE__FERNET_KEY=b0a_36xVARWfsP1QRhS2GM3MwrDzsO0KGM4PPpwE0Uc=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=2
    volumes:
      - ./airflow_data:/opt/airflow
    #network_mode: host
    networks:
      - click_network
    depends_on:
      - airflow
    command: triggerer

  flower:
    image: apache/airflow:2.3.0
    container_name: airflow_flower
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow

      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0

      - AIRFLOW__CORE__FERNET_KEY=b0a_36xVARWfsP1QRhS2GM3MwrDzsO0KGM4PPpwE0Uc=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "5555:5555"
    #network_mode: host
    networks:
      - click_network
    command: celery flower

  superset:
    build:
      context: .
      dockerfile: Dockerfile-superset
    container_name: superset
    environment:
      - SUPERSET_WEBSERVER_PORT=8088
      - SECRET_KEY=ZohcCnWuX7xLX3b4mqbXsbn6iaKfyyZ8mvFb4e24Y5j6myoQ/w2DsSLd
    ports:
      - "8088:8088"
    volumes:
      - ./superset_data:/var/lib/superset
      - ./superset_config.py:/app/pythonpath/superset_config.py
    #network_mode: host
    networks:
      - click_network
    command: superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
    
networks:
  click_network:
    driver: bridge

