services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    network_mode: host

  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile-clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    network_mode: host
    command: /bin/bash -c "/entrypoint.sh"

  python:
    image: python:3.9-slim
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    network_mode: host
    command: tail -f /dev/null

  airflow:
    image: apache/airflow:2.3.0
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@127.0.0.1:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=g3rxS2JU0QK-zfqkJaDeOIiUkS2Ft8lBAu2n_COAFpo=
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_data:/opt/airflow
    network_mode: host
    depends_on:
      - postgres
    command: ["bash", "-c", "airflow db init && airflow webserver"]


  superset:
    build:
      context: .
      dockerfile: Dockerfile-superset
    container_name: superset
    environment:
      - SUPERSET_WEBSERVER_PORT=8088
      - SECRET_KEY=ZohcCnWuX7xLX3b4mqbXsbn6iaKfyyZ8mvFb4e24Y5j6myoQ/w2DsSLd
    ports:
      - "8088:8088"
    volumes:
      - ./superset_data:/var/lib/superset
      - ./superset_config.py:/app/pythonpath/superset_config.py
    network_mode: host
    command: superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger





